- name: conditions
  hosts: 172.31.2.131
  tasks:
    - name: check if user exists
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - name: print the command output
      ansible.builtin.debug:
        msg: "output is {{ out }}"

    - name: print output return code
      ansible.builtin.debug:
        msg: "{{ out.rc }}"

    - name: create a user
      become: yes
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0


