---
- name: install nginix
  hosts: 174.25.45.18
  become: yes
  tasks:
    - name: git install
      ansible.builtin.yum:
        - name: git
          state: installed
    - name: start git
      ansible.builtin.systemd:
        - name: git
          state: started