---
- name: Install Nexus Repository Manager
  hosts: target_servers
  become: yes

  tasks:
    - name: Update the package index
      ansible.builtin.yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Java
      ansible.builtin.yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Create nexus user
      ansible.builtin.user:
        name: nexus
        shell: /bin/bash

    - name: Download Nexus
      ansible.builtin.get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /tmp/nexus.tar.gz

    - name: Extract Nexus
      ansible.builtin.unarchive:
        src: /tmp/nexus.tar.gz
        dest: /opt/
        remote_src: yes
        creates: /opt/nexus-3.x.x

    - name: Create symbolic link to nexus
      ansible.builtin.command: ln -s /opt/nexus-3.x.x /opt/nexus
      args:
        creates: /opt/nexus

    - name: Set Nexus permissions
      ansible.builtin.command: chown -R nexus:nexus /opt/nexus-3.x.x /opt/sonatype-work
      args:
        creates: /opt/sonatype-work

    - name: Copy nexus.rc file
      ansible.builtin.copy:
        content: |
          run_as_user="nexus"
        dest: /opt/nexus/bin/nexus.rc
        owner: nexus
        group: nexus

    - name: Create Nexus systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/nexus.service
        content: |
          [Unit]
          Description=nexus service
          After=network.target

          [Service]
          Type=forking
          LimitNOFILE=65536
          ExecStart=/opt/nexus/bin/nexus start
          ExecStop=/opt/nexus/bin/nexus stop
          User=nexus
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target
      owner: root
      group: root
      mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable Nexus service
      ansible.builtin.systemd:
        name: nexus
        enabled: yes

    - name: Start Nexus service
      ansible.builtin.systemd:
        name: nexus
        state: started

