---
- name: install nginix 
  hosts: dev
  become: yes
  tasks:
  - name: install nginix
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: start nginix
    ansible.builtin.systemd:
      name: nginx
      state: stooped
      enabled: yes
