- name: varibles priniting
  hosts: 13.233.151.6
  vars: # play level varibles
  - name: sai
    course: Devops 
    duration: 110hrs
  tasks:
  - name: the name of trainer and course
    ansible.builtin.debug:
      msg: "the name of trainer is {{Name}}"
  - name: the course name is 
    ansible.builtin.debug:
      msg: "the course name is {{course}}"
  - name: the duration of course is 
    ansible.builtin.debug:
      msg: "the duration is {{duration}}"
