- name: varibles at task level
  hosts: dev
  vars: #playbook level varibles 
  - money: "10000 RS"
    land: "5 acres"
  tasks:
  - name: values are taking from playlevel
    ansible.builtin.debug:
     msg: "the money the have is {{money}} and the land is {{land}}"
  - name: inherit values from palylevel and override in task level
    vars: # task level varibles overrided here 
    - money: "20000 RS"
      land: "5 acres"
    tasks:
    - name: task level overrided 
      ansible.builtin.debug:
       msg: "the money of inherited  is {{money}} and land is {{land}}"

       